package com.clinic.app;

import java.time.LocalDate;

public class Patient {
    
    private int id; 
    private final String firstName;
    private final String lastName;
    private final int age;
    private final String sex;
    private final LocalDate lastVisit;

    // 1. Constructor for loading from the database (includes ID)
    public Patient(int id, String firstName, String lastName, int age, String sex, LocalDate lastVisit) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.age = age;
        this.sex = sex;
        this.lastVisit = lastVisit;
    }

    // 2. Constructor for creating a new patient (ID is generated by the DB)
    public Patient(String firstName, String lastName, int age, String sex, LocalDate lastVisit) {
        // ID is set to 0, which tells the DAO it's a new record
        this(0, firstName, lastName, age, sex, lastVisit); 
    }

    // --- Getters ---
    public int getId() { return id; }
    public String getFirstName() { return firstName; }
    public String getLastName() { return lastName; }
    public int getAge() { return age; }
    public String getSex() { return sex; }
    public LocalDate getLastVisit() { return lastVisit; }
    
    // Setter for ID (for when the DB assigns a new ID, if needed, but not strictly necessary here)
    public void setId(int id) { this.id = id; }
}